[package]
name = "adventofcode2020"
version = "0.1.0"
authors = ["Jeremy Burns <j@jaburns.net>"]
edition = "2018"

[dependencies]
modinverse = "0.1.1"
num = "0.3.1"
num-derive = "0.3.3"
num-traits = "0.2.14"
pom = "3.2.0"
regex = "1.4.2"