[package]
name = "adventofcode2019"
version = "0.1.0"
authors = ["Jeremy Burns <j@jaburns.net>"]
edition = "2018"

[dependencies]
glium = "0.25.1"
modinverse = "0.1.1"
num = "0.2.0"
num-derive = "0.3.0"
num-traits = "0.2.0"
permutohedron = "0.2.4"
regex = "1.3.1"